pipeline {
  agent {
    dockerfile {
      customWorkspace '/var/lib/jenkins/pwec2/pwec2'
      filename 'Dockerfile'
    }
  }
  stages {
    stage('Test') {
      steps {
        sh '''
          node --version
          git --version
          curl --version
        '''
      }
    }
  }
}
